                                           
services:

  web:                                                    
    image: nginx:latest                                   
    ports:
      - "8080:80"                                        
    volumes:
      - ./html:/usr/share/nginx/html:ro                  
    networks:
      - mynetwork                                         

  redis:                                                  
    image: redis:latest                                   
    networks:
      - mynetwork                                         

  mysql:                                                  
    image: mysql:8.0                                      
    environment:                                         
      MYSQL_ROOT_PASSWORD: example_root_pwd               
      MYSQL_DATABASE: example_db                          
      MYSQL_USER: app_user                                
      MYSQL_PASSWORD: example_app_pwd                     
    volumes:
      - mysql_data:/var/lib/mysql                        
    networks:
      - mynetwork                                         

volumes:                                                 
  mysql_data:                                             

networks:                                                 
  mynetwork:                                             
    driver: bridge
